# Generated by Django 4.1 on 2023-11-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0017_alter_course_date_generated'),
        ('sections', '0002_section_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('module_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('module_content', models.CharField(max_length=1000)),
                ('module_image', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField()),
                ('belong_to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_modules', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='is_completed',
            field=models.ManyToManyField(related_name='modules_completed', through='modules.Module_completed', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='module',
            name='part_of_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_modules', to='sections.section'),
        ),
    ]
