# Generated by Django 4.1 on 2023-11-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_image',
            field=models.ImageField(blank=True, upload_to='photos/modules'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/modules'),
        ),
    ]
