# Generated by Django 4.1 on 2023-11-10 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_module_image_alter_module_module_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
