# Generated by Django 4.1 on 2023-09-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email_field', models.EmailField(max_length=254, unique=True)),
                ('otp_field', models.CharField(max_length=6)),
                ('time_generated', models.DateTimeField()),
                ('is_OTP_verfified', models.BooleanField(default=False)),
            ],
        ),
    ]
