# Generated by Django 4.1 on 2023-10-11 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 21, 59, 4, 598080, tzinfo=datetime.timezone.utc)),
        ),
    ]
