# Generated by Django 4.1 on 2023-10-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_img_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 18, 11, 12, 42443, tzinfo=datetime.timezone.utc)),
        ),
    ]
