# Generated by Django 4.1 on 2023-10-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_date_generated_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 19, 24, 40, 230236, tzinfo=datetime.timezone.utc)),
        ),
    ]
