# Generated by Django 4.1 on 2023-10-14 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_date_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 20, 18, 2, 655724, tzinfo=datetime.timezone.utc)),
        ),
    ]
