# Generated by Django 4.1 on 2023-10-15 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_iscomplete_alter_course_date_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.CharField(choices=[('Age < 10', 'Age <10'), ('10 < Age < 15', '10 < Age < 15'), ('15 < Age < 18', '15 < Age < 18'), ('Above 18', 'Above 18'), ('For all ages', 'For all ages')], default='For all ages', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 22, 19, 894063, tzinfo=datetime.timezone.utc)),
        ),
    ]
