# Generated by Django 4.1 on 2023-10-16 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_age_group_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 20, 50, 4, 49698, tzinfo=datetime.timezone.utc)),
        ),
    ]
