# Generated by Django 4.1 on 2023-11-08 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 17, 33, 7, 643009, tzinfo=datetime.timezone.utc)),
        ),
    ]
