# Generated by Django 4.1 on 2023-11-08 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 9, 24, 410423, tzinfo=datetime.timezone.utc)),
        ),
    ]
