# Generated by Django 4.1 on 2023-11-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 19, 3, 25, 274732, tzinfo=datetime.timezone.utc)),
        ),
    ]
