# Generated by Django 4.1 on 2023-11-10 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 12, 17, 2, 859890, tzinfo=datetime.timezone.utc)),
        ),
    ]
