# Generated by Django 4.1 on 2024-01-06 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 21, 13, 15, 923595, tzinfo=datetime.timezone.utc)),
        ),
    ]
