# Generated by Django 4.1 on 2023-10-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0011_alter_course_date_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('section_description', models.CharField(max_length=200)),
                ('Difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Easy', max_length=20)),
                ('available_to_student', models.ManyToManyField(through='sections.Available_sections', to='accounts.student')),
                ('belong_to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_sections', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='students_completed',
            field=models.ManyToManyField(related_name='sections_completed', through='sections.Section_completed', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='available_sections',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_with_access', to='sections.section'),
        ),
        migrations.AddField(
            model_name='available_sections',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_sections', to='accounts.student'),
        ),
        migrations.AlterUniqueTogether(
            name='available_sections',
            unique_together={('student', 'section')},
        ),
    ]
